#!name=xueqiu
#!desc=雪球去广告
#!quote=@RuCu6
[MITM]
hostname = %APPEND% *.xueqiu.com



[Rule]
URL-REGEX,^https:\/\/api.xueqiu.com\/ucprofile\/api\/user\/batchGetUserBasicInfo.json,Reject
URL-REGEX,^https:\/\/api\.xueqiu\.com\/statuses\/livenews\/mark\/list\.json\?,Reject
URL-REGEX,^https:\/\/api\.xueqiu\.com\/snowflake-theme\/query\/v1\/hot_event\/rich_tag_new\.json\?,Reject
URL-REGEX,^https:\/\/api\.xueqiu\.com\/recommend-proxy\/card\/zj_card\.json\?,Reject
URL-REGEX,^https:\/\/api\.xueqiu\.com\/analysis\/build_union\/dialog\/show\.json\?,Reject
URL-REGEX,^https:\/\/api\.xueqiu\.com\/snowpard\/launch_strategy\/query\.json\?,Reject
URL-REGEX,^https:\/\/fund\.xueqiu\.com\/fundx,Reject
URL-REGEX,^https:\/\/api\.xueqiu\.com\/ucprofile\/api\/user\/batch_get_profile_image\.json,Reject
URL-REGEX,^https:\/\/api\.xueqiu\.com\/recommend-proxy\/card\/zj_card\.json,Reject
URL-REGEX,^https:\/\/open\.xueqiu\.com\/mpaas\/rn\/releases\/v2\/match_bundles,Reject