#!name=xueqiu
#!desc=雪球去广告
#!quote=@RuCu6
[MITM]
hostname = %APPEND% *.xueqiu.com

[URL Rewrite]
^https:\/\/api.xueqiu.com\/ucprofile\/api\/user\/batchGetUserBasicInfo.json url reject-dict
^https:\/\/api\.xueqiu\.com\/statuses\/livenews\/mark\/list\.json\? url reject-dict
^https:\/\/api\.xueqiu\.com\/snowflake-theme\/query\/v1\/hot_event\/rich_tag_new\.json\? url reject-dict
^https:\/\/api\.xueqiu\.com\/recommend-proxy\/card\/zj_card\.json\? url reject-dict
^https:\/\/api\.xueqiu\.com\/analysis\/build_union\/dialog\/show\.json\? url reject-dict
^https:\/\/api\.xueqiu\.com\/snowpard\/launch_strategy\/query\.json\? url reject-dict
^https:\/\/fund\.xueqiu\.com\/fundx url reject-dict
^https:\/\/api\.xueqiu\.com\/ucprofile\/api\/user\/batch_get_profile_image\.json url reject-dict
^https:\/\/api\.xueqiu\.com\/recommend-proxy\/card\/zj_card\.json url reject-dict
^https:\/\/open\.xueqiu\.com\/mpaas\/rn\/releases\/v2\/match_bundles url reject-dict